"""Initial Migration

Revision ID: 33696e2c8d73
Revises: d6a1f8d0399d
Create Date: 2021-11-04 07:36:29.171390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33696e2c8d73'
down_revision = 'd6a1f8d0399d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
